export default {
  name: 'pricing',
  title: 'Pricing',
  type: 'document',
  fields: [
    {
      name: 'planName',
      title: 'Plan Name',
      type: 'string',
      description: 'e.g., "Professional Package", "Starter Plan"',
      validation: (Rule: any) => Rule.required(),
      initialValue: 'Professional Package',
    },
    {
      name: 'currency',
      title: 'Currency',
      type: 'string',
      description: 'Select currency symbol',
      options: {
        list: [
          {title: 'Rands (R)', value: 'R'},
          {title: 'Dollars ($)', value: '$'},
        ],
        layout: 'radio',
      },
      validation: (Rule: any) => Rule.required(),
      initialValue: '$',
    },
    {
      name: 'price',
      title: 'Price',
      type: 'number',
      description: 'Base price amount (numbers only)',
      validation: (Rule: any) => Rule.required().min(0),
      initialValue: 3200,
    },
    {
      name: 'period',
      title: 'Period Label',
      type: 'string',
      description: 'e.g., "/project", "/month", "/year", "/quarter"',
      validation: (Rule: any) => Rule.required(),
      initialValue: '/project',
    },
    {
      name: 'timeline',
      title: 'Timeline/Delivery',
      type: 'string',
      description: 'e.g., "4–6 weeks", "2 weeks"',
      validation: (Rule: any) => Rule.required(),
      initialValue: '4–6 weeks',
    },
    {
      name: 'features',
      title: 'Features',
      type: 'array',
      of: [{type: 'string'}],
      description: 'List of features included in this plan',
      validation: (Rule: any) => Rule.required().min(1),
    },
    {
      name: 'ctaText',
      title: 'CTA Button Text',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
      initialValue: 'Start conversation',
    },
    {
      name: 'ctaLink',
      title: 'CTA Button Link',
      type: 'string',
      description: 'URL or hash (e.g., "#contact", "/contact")',
      validation: (Rule: any) => Rule.required(),
      initialValue: '#contact',
    },
    {
      name: 'upsellEnabled',
      title: 'Enable Upsell Add-on',
      type: 'boolean',
      description: 'Show optional upsell/add-on section',
      initialValue: false,
    },
    {
      name: 'upsellName',
      title: 'Upsell Name',
      type: 'string',
      description: 'e.g., "Growth Package", "SEO Optimization"',
      hidden: ({document}: any) => !document?.upsellEnabled,
    },
    {
      name: 'upsellDescription',
      title: 'Upsell Description',
      type: 'text',
      rows: 2,
      hidden: ({document}: any) => !document?.upsellEnabled,
    },
    {
      name: 'upsellPrice',
      title: 'Upsell Price',
      type: 'number',
      description: 'Additional cost for the upsell',
      hidden: ({document}: any) => !document?.upsellEnabled,
    },
    {
      name: 'order',
      title: 'Order',
      type: 'number',
      description: 'Display order (lower numbers appear first)',
      validation: (Rule: any) => Rule.required().min(0),
      initialValue: 1,
    },
  ],
  orderings: [
    {
      title: 'Order',
      name: 'order',
      by: [{field: 'order', direction: 'asc'}],
    },
  ],
  preview: {
    select: {
      title: 'planName',
      price: 'price',
      period: 'period',
      order: 'order',
    },
    prepare({title, price, period, order}: any) {
      return {
        title: `${order}. ${title}`,
        subtitle: `$${price.toLocaleString()}${period}`,
      }
    },
  },
}
